# Generated by Django 2.1.7 on 2019-04-14 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerating',
            name='service_job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceJob'),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
