# Generated by Django 2.1.7 on 2019-04-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190414_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workercompleterating',
            name='service_worker',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='client',
        ),
        migrations.RemoveField(
            model_name='servicejob',
            name='client_request',
        ),
        migrations.RemoveField(
            model_name='servicejob',
            name='service_worker',
        ),
        migrations.RemoveField(
            model_name='servicerating',
            name='service_job',
        ),
        migrations.RemoveField(
            model_name='servicerating',
            name='service_worker',
        ),
        migrations.RemoveField(
            model_name='servicerating',
            name='worker_complete_rating',
        ),
        migrations.DeleteModel(
            name='WorkerCompleteRating',
        ),
    ]
