# Generated by Django 2.1.7 on 2019-04-14 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190414_1600'),
        ('services', '0003_auto_20190414_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerCompleteRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('service_worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.ServiceWorker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicejob',
            name='client_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.ClientRequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicejob',
            name='service_worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.ServiceWorker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerating',
            name='service_job',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceJob'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerating',
            name='service_worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.ServiceWorker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerating',
            name='worker_complete_rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.WorkerCompleteRating'),
            preserve_default=False,
        ),
    ]
