# Generated by Django 2.1.7 on 2019-04-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190414_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrequest',
            name='client',
        ),
        migrations.RemoveField(
            model_name='servicejob',
            name='client_request',
        ),
        migrations.RemoveField(
            model_name='servicejob',
            name='service_worker',
        ),
        migrations.RemoveField(
            model_name='servicerating',
            name='service_job',
        ),
        migrations.RemoveField(
            model_name='servicerating',
            name='service_worker',
        ),
        migrations.RemoveField(
            model_name='servicerating',
            name='worker_complete_rating',
        ),
        migrations.RemoveField(
            model_name='workercompleterating',
            name='service_worker',
        ),
        migrations.DeleteModel(
            name='ClientRequest',
        ),
        migrations.DeleteModel(
            name='ServiceJob',
        ),
        migrations.DeleteModel(
            name='ServiceRating',
        ),
        migrations.DeleteModel(
            name='WorkerCompleteRating',
        ),
    ]
