# Generated by Django 2.1.7 on 2019-04-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_auto_20190414_1600'),
        ('services', '0005_auto_20190414_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('requested_start', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True)),
                ('actual_end', models.DateTimeField(blank=True)),
                ('client_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ClientRequest')),
                ('service_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ServiceWorker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('overall_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('quality_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('cost_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('personality_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('service_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceJob')),
                ('service_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ServiceWorker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerCompleteRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='deleted at')),
                ('service_worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.ServiceWorker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='servicerating',
            name='worker_complete_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.WorkerCompleteRating'),
        ),
    ]
